name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "npm dist-tag"
        required: true
        default: "latest"
        type: choice
        options:
          - latest
          - beta
          - alpha

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --tag "${{ inputs.tag }}"
        working-directory: packages/promon
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

